

swagger:
  enabled: true
  title: spring-boot-swagger2-starter
  description: 使用SpringBoot-swagger2-starter
  base-package: com.fengwenyi.apiswaggerstarter
#  base-path: /**
  exclude-path: /ops/**, /error
  version: 1.0
  license: spring-boot-starter-swagger
  license-url: https://github.com/SpringForAll/spring-boot-starter-swagger
  terms-of-service-url: https://swagger.io/
  contact:
    name: Wenyi Feng
    email: xfsy2014@gmail.com
  host: fengwenyi.com
  apply-default-response-messages: false
  global-response-message:
    get[0]:
      code: 401
      message: 401get
    get[1]:
      code: 500
      message: 500get
      modelRef: error
    post[0]:
      code: 500
      message: 500post
      modelRef: error
spring:
  http:
    encoding:
      charset: utf-8